USE projeto_covidao;

SELECT * FROM COVID_DEATHS WHERE LOCATION = 'Low income' ORDER BY 3,4;
SELECT * FROM COVID_VACCINATIONS ORDER BY 3,4;

-- DATA THAT IS GOING TO BE USED 

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM COVID_DEATHS ORDER BY 1,2;

 -- TOTAL CASES X TOTAL DEATHS

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES) * 100 AS DEATH_PERCENTAGE
FROM COVID_DEATHS ORDER BY 1,2;

-- TOTAL CASES X POPULATION
-- SHOWS PERCENTAGE OF PEOPLE WHO GOT COVID IN THE COUNTRIES
SELECT LOCATION, DATE, TOTAL_CASES, POPULATION, (TOTAL_CASES/POPULATION) * 100 AS INFECTED_POPULATION
FROM COVID_DEATHS 
WHERE Location = 'brazil'
ORDER BY 1,2;

-- COUNTRIES WITH MAX PERCENTAGE OF INFECTED 

SELECT LOCATION, MAX(TOTAL_CASES) AS HIGHEST_INFECTION_PERCENT, POPULATION, (MAX(TOTAL_CASES)/POPULATION) * 100 AS INFECTED_POPULATION
FROM COVID_DEATHS 
GROUP BY LOCATION, POPULATION
ORDER BY 4 DESC;

-- COUNTRIES WITH MAX DEATH COUNT 

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTAL_DEATH_COUNT
FROM COVID_DEATHS
WHERE continent <> ''
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

-- DATA BY CONTINENT
-- DEATH COUNT 

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTAL_DEATH_COUNT
FROM COVID_DEATHS
WHERE LOCATION IN ('WORLD', 'EUROPE', 'NORTH AMERICA', 'ASIA', 'SOUTH AMERICA', 'AFRICA', 'OCEANIA')
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

--GLOBAL NUMBERS PER DAY (DEATH PERCENTAGE)

USE projeto_covidao;
SELECT DATE, SUM(CAST(NEW_CASES AS INT)) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS,
SUM(CAST(NEW_DEATHS AS float))/SUM(CAST(NEW_CASES AS float))*100 AS DEATH_PERCENTAGE
FROM covid_deaths
WHERE continent <> ''
GROUP BY DATE
ORDER BY 1,2;



-- VACCINATION NUMBERS 
-- JOINING TABLES 

SELECT *
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
	ON DEA.LOCATION = VAC.LOCATION AND DEA.DATE = VAC.DATE;

-- TOTAL POPULATION VS VACCINATIONS (GLOBAL AND BRAZIL)

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS 
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
	ON DEA.LOCATION = VAC.LOCATION AND DEA.DATE = VAC.DATE
WHERE DEA.continent <> ''
ORDER BY 2,3

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS 
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
	ON DEA.LOCATION = VAC.LOCATION AND DEA.DATE = VAC.DATE
WHERE DEA.LOCATION ='BRAZIL'
ORDER BY 2,3

-- COUNTING VACCINATION PER COUNTRY 

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS
, SUM(CONVERT(FLOAT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS SUM_OF_VACCINATIONS
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
	ON DEA.LOCATION = VAC.LOCATION AND DEA.DATE = VAC.DATE
WHERE DEA.continent <> ''
ORDER BY 2,3

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS
, SUM(CONVERT(FLOAT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS SUM_OF_VACCINATIONS
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
	ON DEA.LOCATION = VAC.LOCATION AND DEA.DATE = VAC.DATE
WHERE DEA.LOCATION = 'BRAZIL'
ORDER BY 2,3

-- CREATING TEMP TABLE TO PERFORM CALCULATION
DROP TABLE IF EXISTS #VACCINATIONS_POPULATION
CREATE TABLE #VACCINATIONS_POPULATION
(CONTINENT NVARCHAR(150),
LOCATION NVARCHAR(50),
DATE DATETIME,
POPULATION INT,
NEW_VACCINATIONS FLOAT,
SUM_OF_VACCINATION NUMERIC);

INSERT INTO #VACCINATIONS_POPULATION
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS
, SUM(CONVERT(FLOAT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS SUM_OF_VACCINATIONS
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
	ON DEA.LOCATION = VAC.LOCATION AND DEA.DATE = VAC.DATE
WHERE DEA.continent <> '';

Select *, (SUM_OF_VACCINATION/Population)*100
From #VACCINATIONS_POPULATION;


